#!/usr/bin/env bash
# compose — build the central prompt variants from parts/.
#
# Two axes, deliberately separate:
#
#   AUDIENCE   aspect | worker      who is reading (persists vs one-shot run)
#   TIER       lean   | scaffolded  how much working discipline to spell out
#
# The tier axis exists because not every run is Claude. As of 2026-07-26 the
# fleet is ornith (the whole pool), codex-cli, claude-opus-4-7 and
# claude-sonnet-4-6 — and NO Claude 5 model at all. Anthropic's guidance to
# delete rules in favour of judgement is calibrated for the Claude 5
# generation; applying it to models we actually run would remove scaffolding
# they still use. So the rules were not deleted, they were MOVED into
# parts/scaffold.md, which composes into the scaffolded variant only.
#
# When a frontier model runs a role, serve it the lean variant. When ornith
# or codex does, serve the scaffolded one. Nothing selects automatically yet
# — the resolver picks by identity name, not model (NEX-827); wiring
# Provider/Model into that choice is the follow-up.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
P=central/parts

emit() { # emit <outfile> <part>...
  local out="$1"; shift
  {
    echo "<!-- GENERATED by compose.sh from ${*} — edit the parts, not this file. -->"
    echo
    for part in "$@"; do
      cat "${P}/${part}.md"
      echo
    done
  } > "central/${out}"
  printf "  %-34s %6s bytes\n" "central/${out}" "$(wc -c < "central/${out}")"
}

emit composed-aspect.draft.md            common aspect
emit composed-worker.draft.md            common worker
emit composed-worker-scaffolded.draft.md common worker scaffold

echo
echo "Reminder: composing does not deploy. Apply with promptsync.sh, and see"
echo "README.md for which column each variant belongs in."
