// Keyfile minting + envelope shape.
//
// Per agent-network/docs/2026-05-08-nexus-resident-personality-spec.md §4 and §9.1.
//
// A keyfile is a JSON document with two layers:
//
//   - plaintext envelope: { nexus_url, nexus_id, issued_at } — agentfunnel
//     reads this without decryption to learn which Nexus to dial
//   - encrypted_payload: NaCl crypto_box_seal of the inner JSON
//     { aspect_name, aspect_privkey, keyfile_version, minted_at, nexus_id },
//     sealed against the Nexus server pubkey (X25519-derived from Ed25519)
//
// SealAnonymous (golang.org/x/crypto/nacl/box) is interoperable with
// libsodium's crypto_box_seal — the spec name. Decryption (Part 4) uses
// the matching Open + the X25519-converted server *private* key.
//
// Ed25519→X25519 pubkey conversion goes through filippo.io/edwards25519:
// decode the Ed25519 pubkey as an Edwards point and emit Montgomery bytes.
// Naive `pubkey[:32]` slicing produces garbage — this is the standard
// footgun the spec warns about.

package aspects

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"crypto/sha512"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"filippo.io/edwards25519"
	"golang.org/x/crypto/nacl/box"
)

// KeyfileFormat is the on-disk format identifier. Bump when the wire
// shape changes incompatibly.
const KeyfileFormat = "nexus-keyfile-v1"

// KeyfileVersion is the schema version embedded in the envelope.
const KeyfileVersion = 1

// Envelope is the plaintext routing layer. Readable by anyone with the
// keyfile; editing it doesn't grant identity, just causes the holder to
// dial the wrong Nexus where decryption fails.
type Envelope struct {
	NexusURL string `json:"nexus_url"`
	NexusID  string `json:"nexus_id"`
	IssuedAt string `json:"issued_at"` // RFC 3339 UTC
}

// Keyfile is the full on-disk JSON document.
type Keyfile struct {
	Version          int      `json:"version"`
	Format           string   `json:"format"`
	Envelope         Envelope `json:"envelope"`
	EncryptedPayload string   `json:"encrypted_payload"` // base64
}

// Payload is the inner JSON sealed inside EncryptedPayload. After
// decryption the Nexus parses this struct to authorize the connection.
type Payload struct {
	AspectName     string `json:"aspect_name"`
	AspectPrivkey  string `json:"aspect_privkey"`  // base64-encoded 32-byte Ed25519 seed (per spec §4). Reconstruct via ed25519.NewKeyFromSeed.
	KeyfileVersion int64  `json:"keyfile_version"` // matches aspects.current_keyfile_version at mint time
	MintedAt       string `json:"minted_at"`       // RFC 3339 UTC
	NexusID        string `json:"nexus_id"`        // mutual-auth: aspect verifies envelope.nexus_id == payload.nexus_id
}

// MintInput is the data needed to mint a keyfile. Caller assembles it
// from the Identity + the freshly-bumped aspects row.
type MintInput struct {
	// AspectName is the registry name (e.g. "plumb").
	AspectName string

	// KeyfileVersion is the version this keyfile is being minted at —
	// the value already-bumped in the aspects row. Older versions are
	// dead the moment Nexus stores this; that's the auto-revoke primitive.
	KeyfileVersion int64

	// AspectPrivkey is the freshly-generated aspect private key. The
	// full 64-byte Ed25519 representation (seed || pubkey).
	AspectPrivkey ed25519.PrivateKey

	// ServerPubkey is the Nexus's Ed25519 server public key, loaded
	// from nexus_identity.server_pubkey. Mint converts to X25519 before
	// sealing.
	ServerPubkey ed25519.PublicKey

	// NexusID is the stable UUID identifying this Nexus instance.
	NexusID string

	// NexusURL is the wss://... endpoint agentfunnel dials.
	NexusURL string

	// MintedAt is the UTC timestamp written into both envelope.issued_at
	// and payload.minted_at. Caller controls (so tests can pin).
	MintedAt time.Time
}

// Mint constructs and seals a keyfile. Reads randomness from rand.Reader
// for the sealed-box ephemeral keypair (handled internally by nacl/box).
//
// Returns the assembled Keyfile, ready for JSON marshaling, plus the
// fingerprint (hex SHA-256 of the encrypted payload) for terminal display.
//
// Errors fall into three buckets: bad inputs (wrong key sizes), curve
// conversion failure (server pubkey isn't a valid Edwards point — should
// never happen for a key generated by ed25519.GenerateKey), and seal
// failure (rand source exhausted — should never happen).
func Mint(in MintInput) (*Keyfile, string, error) {
	return mintWithRand(in, rand.Reader)
}

// mintWithRand is the rand-injectable variant. Tests use a deterministic
// reader to make the sealed payload reproducible for round-trip
// validation; production callers go through Mint with crypto/rand.
func mintWithRand(in MintInput, r io.Reader) (*Keyfile, string, error) {
	if in.AspectName == "" {
		return nil, "", fmt.Errorf("aspects.Mint: AspectName empty")
	}
	if len(in.AspectPrivkey) != ed25519.PrivateKeySize {
		return nil, "", fmt.Errorf("aspects.Mint: AspectPrivkey wrong size: got %d want %d",
			len(in.AspectPrivkey), ed25519.PrivateKeySize)
	}
	if len(in.ServerPubkey) != ed25519.PublicKeySize {
		return nil, "", fmt.Errorf("aspects.Mint: ServerPubkey wrong size: got %d want %d",
			len(in.ServerPubkey), ed25519.PublicKeySize)
	}
	if in.NexusID == "" {
		return nil, "", fmt.Errorf("aspects.Mint: NexusID empty")
	}
	if in.NexusURL == "" {
		return nil, "", fmt.Errorf("aspects.Mint: NexusURL empty")
	}
	if in.KeyfileVersion <= 0 {
		return nil, "", fmt.Errorf("aspects.Mint: KeyfileVersion must be positive, got %d", in.KeyfileVersion)
	}

	mintedAt := in.MintedAt.UTC().Format(time.RFC3339)

	// Spec §4: aspect_privkey is the 32-byte Ed25519 seed (canonical
	// portable form). agentfunnel reconstructs the full key with
	// ed25519.NewKeyFromSeed. Encoding the full 64-byte Go form here
	// would diverge from the spec and break interop with non-Go
	// validators.
	payload := Payload{
		AspectName:     in.AspectName,
		AspectPrivkey:  base64.StdEncoding.EncodeToString(in.AspectPrivkey.Seed()),
		KeyfileVersion: in.KeyfileVersion,
		MintedAt:       mintedAt,
		NexusID:        in.NexusID,
	}
	payloadJSON, err := json.Marshal(payload)
	if err != nil {
		return nil, "", fmt.Errorf("aspects.Mint: marshal payload: %w", err)
	}

	// Convert server Ed25519 pubkey to X25519 (Montgomery) form.
	recipient, err := edPubkeyToX25519(in.ServerPubkey)
	if err != nil {
		return nil, "", fmt.Errorf("aspects.Mint: convert server pubkey to X25519: %w", err)
	}

	sealed, err := box.SealAnonymous(nil, payloadJSON, &recipient, r)
	if err != nil {
		return nil, "", fmt.Errorf("aspects.Mint: seal payload: %w", err)
	}
	encoded := base64.StdEncoding.EncodeToString(sealed)

	kf := &Keyfile{
		Version: KeyfileVersion,
		Format:  KeyfileFormat,
		Envelope: Envelope{
			NexusURL: in.NexusURL,
			NexusID:  in.NexusID,
			IssuedAt: mintedAt,
		},
		EncryptedPayload: encoded,
	}

	sum := sha256.Sum256(sealed)
	fingerprint := hex.EncodeToString(sum[:])
	return kf, fingerprint, nil
}

// EdPrivkeyToX25519 converts an Ed25519 private key to its X25519
// scalar form for crypto_box decryption.
//
// Recipe (libsodium crypto_sign_ed25519_sk_to_curve25519):
//
//   1. Take the 32-byte Ed25519 seed (priv.Seed()).
//   2. SHA-512 the seed.
//   3. Take the first 32 bytes of the digest.
//   4. Clamp: clear bits 0,1,2 of byte 0; clear bit 7 of byte 31; set bit 6 of byte 31.
//
// The returned [32]byte is the X25519 private scalar suitable for
// crypto/nacl/box.OpenAnonymous as the recipient privkey. Pairs with
// edPubkeyToX25519 — Mint converts the server pubkey, Validate
// converts the server privkey, and the seal/open round-trips.
//
// FOOTGUN: do NOT pass priv[:32] as an X25519 scalar. That's the seed,
// not the clamped scalar; using it directly will silently produce a
// different X25519 keypair than the one paired with the converted
// pubkey, and decryption will fail or (worse, in some weak setups)
// succeed against an unintended recipient.
func EdPrivkeyToX25519(priv ed25519.PrivateKey) [32]byte {
	var out [32]byte
	digest := sha512.Sum512(priv.Seed())
	copy(out[:], digest[:32])
	out[0] &= 248
	out[31] &= 127
	out[31] |= 64
	return out
}

// EdPubkeyToX25519 is the exported counterpart to EdPrivkeyToX25519,
// converting an Ed25519 public key to its X25519 (Montgomery) form.
// Wraps the package-internal helper.
func EdPubkeyToX25519(pub ed25519.PublicKey) ([32]byte, error) {
	return edPubkeyToX25519(pub)
}

// edPubkeyToX25519 converts an Ed25519 public key to its X25519
// (Montgomery) form for use as a crypto_box recipient.
//
// The standard recipe: decode the 32-byte Ed25519 pubkey as an Edwards
// curve point, then emit Bytes in Montgomery form. The edwards25519
// package handles the y-coordinate rewriting; we never touch the field
// arithmetic ourselves.
//
// Important: this is for the *public* key. Private-key conversion
// (needed by Part 4 when decrypting) is a different operation — it
// goes through SHA-512 of the Ed25519 seed + clamping. Do not slice
// the Ed25519 seed and pass it to curve25519 functions directly.
func edPubkeyToX25519(pub ed25519.PublicKey) ([32]byte, error) {
	var out [32]byte
	if len(pub) != ed25519.PublicKeySize {
		return out, fmt.Errorf("ed→x25519: wrong pubkey size %d", len(pub))
	}
	pt, err := new(edwards25519.Point).SetBytes(pub)
	if err != nil {
		return out, fmt.Errorf("ed→x25519: invalid Edwards point: %w", err)
	}
	mb := pt.BytesMontgomery()
	if len(mb) != 32 {
		return out, fmt.Errorf("ed→x25519: Montgomery bytes wrong length %d", len(mb))
	}
	copy(out[:], mb)
	return out, nil
}
